CREATE TABLE DATA_MODEL
        (
        PRIMARY_KEY VARCHAR(10) NOT NULL,
        NAME VARCHAR2(50) NOT NULL,
        DESCRIPTION VARCHAR2(50) NOT NULL,
        TIMESTAMP_DATE TIMESTAMP,
        PRIMARY KEY(PRIMARY_KEY)
        );